version: '2'
services:
  postgraphql:    
    image: docker_postgraphql
    networks:
      - missioncontrol
    ports:
      - "3000:3000/tcp"
    links:
      - "pgbouncer:pgb"
    environment:
      POSTGRES_DB: postgres
      PG_SCHEMA: mission_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgbouncer:    
    image: docker_pgbouncer
    networks:
      - missioncontrol
    ports:
      - "6432:6432/tcp"
    links:
      - "postgres:pg"
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
      #  PG_PORT_5432_TCP_ADDR: tcp://pg
      #  PG_ENV_POSTGRESQL_USER: postgres
      #  PG_ENV_POSTGRESQL_PASS: postgres
      #  POSTGRES_PORT: tcp://pg:5432
      #  POSTGRES_ENV_POSTGRES_USER: postgres
      #  POSTGRES_ENV_POSTGRES_DB: postgres
      #  POSTGRES_ENV_POSTGRES_PASSWORD: postgres
  postgres:
    image: docker_postgres
    networks:
      - missioncontrol
    ports:
      - "5432:5432"
    # volumes:
      # - postgres-data:/var/lib/postgresql/9.5/data
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
volumes:
  postgres-data:
    driver: local
  pgbouncer-rr-data:
    driver: local
networks:
  missioncontrol:
    driver: bridge
